version: '3.9'
services:
  post-database:
    image: postgres:14.2
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: "post"

  post-service:
    depends_on:
      - post-database
    build:
      context: .
      dockerfile: post-service/Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ENABLE_SWAGGER: true

networks:
  default:
    name: twiddit
