version: '3.9'
services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: "post"

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME:-admin@admin.nl}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_SERVER_JSON_FILE: /tmp/servers.json
    ports:
      - "5050:80"
    volumes:
      - "./servers.json:/tmp/servers.json"

  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: post-service/Dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
